### ISSUE TITLE
Latest version of fleetctl for Mac OS X

### ISSUE THREAD

**Issue by justjoheinz** [rimusz/coreos-osx-gui-cluster#7]
At https://github.com/coreos/fleet/releases
the 0.10.2 does not have a binary archive anymore (as opposed to 0.10.1). Hence the update script fails to install fleetctl locally. I do not know if this is just some temporary glitch at the coreos git repo, or if you need another install strategy.

**Comment by rimusz** [comment]
yes, I noticed it yesterday too, no idea why they have not provided binaries on github yet.
I might start including etcdctl and fleetctl OS X binaries within the App, as I do with Kubernetes binaries for my OS X Apps

**Comment by rimusz** [comment]
it was a temporal unavailability of the binaries
